version: '3'

services:

  # PostgreSQL database server
  psql:
    build:
      context: ./psql
      dockerfile: Dockerfile
    environment:
      - PGDATA:/var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./psql/pg_hba.conf:/etc/postgresql/postgresql.conf
      - ./data/pgdata:/pgdata
    restart: unless-stopped

  # Lapis-chan web client
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    depends_on:
      - psql
    volumes:
      - ./web:/var/www
      - ./data:/var/data
    ports:
      - 1001:80
    restart: unless-stopped

volumes:
  postgres:
